dependencies:
  '@rush-temp/coy-test-component-b': 'file:projects/coy-test-component-b.tgz'
  '@rush-temp/project-a': 'file:projects/project-a.tgz'
  '@rush-temp/project-b': 'file:projects/project-b.tgz'
  promise: 6.1.0
packages:
  /asap/1.0.0:
    dev: false
    resolution:
      integrity: sha1-sqRdpf36ILBJb8N2jMJ8EvqRan0=
  /asap/2.0.6:
    dev: false
    resolution:
      integrity: sha1-5QNHYR1+aQlDIIu9r+vLwvuGbUY=
  /core-js/1.2.7:
    deprecated: 'core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.'
    dev: false
    resolution:
      integrity: sha1-ZSKUwUZR2yj6k70tX/KYOk8IxjY=
  /coy-test-component-b/1.0.0:
    dev: false
    resolution:
      integrity: sha512-j+CyPQwee/LqN8x+3Zc3RZKpKbJr1O5vmq1fGAS5fYkG1uWN8cciAu9nN4e5wXl6GlZqwWiOi16xdO/EL98nBw==
  /coy-test-component-b/1.3.0:
    dev: false
    resolution:
      integrity: sha512-voYYffkcoBm/oKhTuD4Xip4cVTWaobxnjsYzKMW4okJcIlvgenaI2Bj+ht+l1Xsutf8/T7RDOcKbcCBSZomMPQ==
  /create-react-class/15.6.3:
    dependencies:
      fbjs: 0.8.17
      loose-envify: 1.4.0
      object-assign: 4.1.1
    dev: false
    resolution:
      integrity: sha512-M+/3Q6E6DLO6Yx3OwrWjwHBnvfXXYA7W+dFjt/ZDBemHO1DDZhsalX/NUtnTYclN6GfnBDRh4qRHjcDHmlJBJg==
  /encoding/0.1.12:
    dependencies:
      iconv-lite: 0.4.24
    dev: false
    resolution:
      integrity: sha1-U4tm8+5izRq1HsMjgp0flIDHS+s=
  /fbjs/0.8.17:
    dependencies:
      core-js: 1.2.7
      isomorphic-fetch: 2.2.1
      loose-envify: 1.4.0
      object-assign: 4.1.1
      promise: 7.3.1
      setimmediate: 1.0.5
      ua-parser-js: 0.7.20
    dev: false
    resolution:
      integrity: sha1-xNWY6taUkRJlPWWIsBpc3Nn5D90=
  /iconv-lite/0.4.24:
    dependencies:
      safer-buffer: 2.1.2
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==
  /is-stream/1.1.0:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-EtSj3U5o4Lec6428hBc66A2RykQ=
  /isomorphic-fetch/2.2.1:
    dependencies:
      node-fetch: 1.7.3
      whatwg-fetch: 3.0.0
    dev: false
    resolution:
      integrity: sha1-YRrhrPFPXoH3KVB0coGf6XM1WKk=
  /js-tokens/4.0.0:
    dev: false
    resolution:
      integrity: sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==
  /loose-envify/1.4.0:
    dependencies:
      js-tokens: 4.0.0
    dev: false
    hasBin: true
    resolution:
      integrity: sha512-lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==
  /node-fetch/1.7.3:
    dependencies:
      encoding: 0.1.12
      is-stream: 1.1.0
    dev: false
    resolution:
      integrity: sha512-NhZ4CsKx7cYm2vSrBAr2PvFOe6sWDf0UYLRqA6svUYg7+/TSfVAu49jYC4BvQ4Sms9SZgdqGBgroqfDhJdTyKQ==
  /object-assign/4.1.1:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-IQmtx5ZYh8/AXLvUQsrIv7s2CGM=
  /promise/6.1.0:
    dependencies:
      asap: 1.0.0
    dev: false
    resolution:
      integrity: sha1-LOcp9rlLRcJoka0GAsXJDgTG7vY=
  /promise/7.3.1:
    dependencies:
      asap: 2.0.6
    dev: false
    resolution:
      integrity: sha512-nolQXZ/4L+bP/UGlkfaIujX9BKxGwmQ9OT4mOt5yvy8iK1h3wqTEJCijzGANTCCl9nWjY41juyAn2K3Q1hLLTg==
  /prop-types/15.7.2:
    dependencies:
      loose-envify: 1.4.0
      object-assign: 4.1.1
      react-is: 16.10.2
    dev: false
    resolution:
      integrity: sha512-8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==
  /react-is/16.10.2:
    dev: false
    resolution:
      integrity: sha512-INBT1QEgtcCCgvccr5/86CfD71fw9EPmDxgiJX4I2Ddr6ZsV6iFXsuby+qWJPtmNuMY0zByTsG4468P7nHuNWA==
  /react/15.6.2:
    dependencies:
      create-react-class: 15.6.3
      fbjs: 0.8.17
      loose-envify: 1.4.0
      object-assign: 4.1.1
      prop-types: 15.7.2
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-26BDSrQ5z+gvEI8PURZjkIF5qnI=
  /react/16.10.2:
    dependencies:
      loose-envify: 1.4.0
      object-assign: 4.1.1
      prop-types: 15.7.2
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha512-MFVIq0DpIhrHFyqLU0S3+4dIcBhhOvBE8bJ/5kHPVOVaGdo0KuiQzpcjCPsf585WvhypqtrMILyoE2th6dT+Lw==
  /safer-buffer/2.1.2:
    dev: false
    resolution:
      integrity: sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==
  /setimmediate/1.0.5:
    dev: false
    resolution:
      integrity: sha1-KQy7Iy4waULX1+qbg3Mqt4VvgoU=
  /ua-parser-js/0.7.20:
    dev: false
    resolution:
      integrity: sha512-8OaIKfzL5cpx8eCMAhhvTlft8GYF8b2eQr6JkCyVdrgjcytyOmPCXrqXFcUnhonRpLlh5yxEZVohm6mzaowUOw==
  /whatwg-fetch/3.0.0:
    dev: false
    resolution:
      integrity: sha512-9GSJUgz1D4MfyKU7KRqwOjXCXTqWdFNvEr7eUBYchQiVc744mqK/MzXPNR2WsPkmkOa4ywfg8C2n8h+13Bey1Q==
  'file:projects/coy-test-component-b.tgz':
    dev: false
    name: '@rush-temp/coy-test-component-b'
    resolution:
      integrity: sha512-n53aJy+A5d0DSUW8IGw6eGakgaMzJhdyxplTcF1gkbgHqnCXIxa+Et5LqHrfVRY5AS0Tg41RDj9kwloclQYBbQ==
      tarball: 'file:projects/coy-test-component-b.tgz'
    version: 0.0.0
  'file:projects/project-a.tgz':
    dependencies:
      coy-test-component-b: 1.0.0
      promise: 6.1.0
      react: 15.6.2
    dev: false
    name: '@rush-temp/project-a'
    resolution:
      integrity: sha512-/GL/LRFQEboUO9LMlTE3mvSyetYUcaGNsbdzVER5wh6A7YJy6LzUlvdKyfhoJuVcIudP4Iz/qesQh75u10TTcQ==
      tarball: 'file:projects/project-a.tgz'
    version: 0.0.0
  'file:projects/project-b.tgz':
    dependencies:
      coy-test-component-b: 1.3.0
      react: 16.10.2
    dev: false
    name: '@rush-temp/project-b'
    resolution:
      integrity: sha512-07/+tR9+bk2Q2Kx2k15/h6joDiQj4y2QSj0pL0XsQ0+TXVkQI9EwDpBrwYpjl76DqGGmqTpAY+rnHAXAlI5l4A==
      tarball: 'file:projects/project-b.tgz'
    version: 0.0.0
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@rush-temp/coy-test-component-b': 'file:./projects/coy-test-component-b.tgz'
  '@rush-temp/project-a': 'file:./projects/project-a.tgz'
  '@rush-temp/project-b': 'file:./projects/project-b.tgz'
  promise: ~6.1.0
